### ISSUE TITLE
Problem with timeout

### ISSUE THREAD

**Issue by Jacopo1891** [bennesp/telegramAPI#1]
I've got some problem with updates:
"/usr/local/lib/ruby/2.2.0/net/http.rb:879:in `initialize': getaddrinfo: Name or service not known (SocketError)
        from /usr/local/lib/ruby/2.2.0/net/http.rb:879:in`open'
        from /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
        from /usr/local/lib/ruby/2.2.0/timeout.rb:73:in`timeout'
        from /usr/local/lib/ruby/2.2.0/net/http.rb:878:in `connect'
        from /usr/local/lib/ruby/2.2.0/net/http.rb:863:in`do_start'
        from /usr/local/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from /usr/local/lib/ruby/2.2.0/open-uri.rb:318:in`open_http'
        from /usr/local/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
        from /usr/local/lib/ruby/2.2.0/open-uri.rb:211:in`block in open_loop'
        from /usr/local/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
        from /usr/local/lib/ruby/2.2.0/open-uri.rb:209:in`open_loop'
        from /usr/local/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
        from /usr/local/lib/ruby/2.2.0/open-uri.rb:716:in`open'
        from /usr/local/lib/ruby/2.2.0/open-uri.rb:34:in `open'
        from /usr/local/lib/ruby/gems/2.2.0/gems/telegramAPI-1.0.15/lib/telegramAPI.rb:39:in`query'
        from /usr/local/lib/ruby/gems/2.2.0/gems/telegramAPI-1.0.15/lib/telegramAPI.rb:56:in `getUpdates'"
Some suggest? Any help would be greatly appreciated.

**Comment by bennesp** [comment]
Please, use right markdown syntax for your code
Anyway, your problem is quite general.

`getaddrinfo: Name or service not known`

It means that your ruby client can't connect to telegram api servers.
Common causes may be
- no internet connection
- local firewall blocking outgoing traffic towards telegram api servers
- problem with dns

Try to open this URL on your browser: https://api.telegram.org/botTOKEN/getMe where TOKEN is the long string given you by [@BotFather](https://telegram.me/botfather)

See the example echo server on the README.md for further explaination of a simple program
